#  contains all random variables
buildings:
  tile_size:
    min_tile_size: 3
    max_tile_size: 12

  foudations:
    collumn_style :
    # proportion of each style
      none: 1
      inner: 1
      outer: 1
      both: 1
    floor:
      min_height: 4
      max_height: 7

  facade:
    windows:
      size:
        min_height: 2
        max_height: 6
        min_width: 1
        max_width: 12
      crossbars:
        min_height_for_vertical_crossbar: 3
        vertical_crossbar: 0.25
        min_width_for_horizontal_crossbar: 3
        horizontal_crossbar: 0.25
      grounded: 0.5
      # alternate between block and pane
      alternate: 0.5
      multiple: 
        # min size and probability of multiple windows on the same vertice
        min_width: 5
        proba: 0.5
      border_radius:
        # proportion of each style
        none: 2
        top: 1
        top_and_bottom: 1
    inter_floor: 0.5
    balcony: 
      proba : 0.25
      growth: 0.8 # [growth]% chance to have min_width + 1 balcony length, [growth**2]% chance to have min_width + 2 balcony length, etc
      size:
        min_len : 1
        max_len : 3
        min_width : 3
      multiple:
      # probability to have multiple balcony IF POSSIBLE
        proba: 0.5
        min_width: 5
        min_gap: 0